version: '3.1'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifi
      MYSQL_USER: notifi
      MYSQL_PASSWORD: notifi
    ports:
      - "127.0.0.1:3306:3306"
    tty: true
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/:ro
    restart: always

  app:
    build:
      context: .
    restart: always
    environment:
      db: notifi:notifi@tcp(db:3306)/notifi
      sentry_dsn: ${sentry_dsn:?err}
      server_key: ${server_key:?err}
      encryption_key: ${encryption_key:?err}
    tty: true
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db