version: '3.2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifi
      MYSQL_USER: notifi
      MYSQL_PASSWORD: notifi
    tty: true
    restart: always
    networks:
      - overlay

  redis:
    image: "redis:alpine"
    networks:
      - overlay

  app:
    image: maxisme/notifi-backend:latest
    restart: always
    environment:
      db: notifi:notifi@tcp(db:3306)/notifi
      sentry_dsn: ${sentry_dsn:?err}
      server_key: ${server_key:?err}
      encryption_key: ${encryption_key:?err}
      redis: "redis:6379"
    deploy:
      mode: global
    tty: true
    ports:
      - "9081:8080"
    networks:
      - overlay
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  # helpers

  shepherd:
    image: mazzolino/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  migrate:
    image: migrate/migrate
    volumes:
      - .sql:/sql
    command: ["-path", "/sql", "-database", "mysql://notifi:notifi@tcp(db:3306)/notifi", "up"]
    links:
      - db

networks:
  overlay: