version: '3.1'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifi
      MYSQL_USER: notifi
      MYSQL_PASSWORD: notifi
    container_name: notifi-backend-db
    ports:
      - "127.0.0.1:3306:3306" # added local exposed ports for migration script
    tty: true
    restart: always

  migrate:
    image: migrate/migrate
    volumes:
      - .sql:/sql
    command: ["-path", "/sql", "-database", "mysql://notifi:notifi@tcp(db:3306)/notifi", "up"]
    links:
      - db

  app:
    build:
      context: .
    restart: always
    environment:
      db: notifi:notifi@tcp(db:3306)/notifi
      sentry_dsn: ${sentry_dsn:?err}
      server_key: ${server_key:?err}
      encryption_key: ${encryption_key:?err}
    tty: true
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db