version: '3.8'
services:
  app:
    image: maxisme/notifi-backend:latest
    env_file:
      - ".env"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.notifibackend.rule=Host(`s.notifi.it`) || (Host(`notifi.it`) && Path(`/api`))"
        - "traefik.http.routers.notifibackend.entrypoints=web-secure"
        - "traefik.http.routers.notifibackend.tls.certresolver=letsencrypt"
        - "traefik.http.services.notifibackend.loadbalancer.server.port=8080"
    networks:
      - traefik

  migrate:
    image: migrate/migrate
    command: ["-path", "/sql", "-database", "mysql://notifi:notifi@tcp(db:3306)/notifi", "up"]

networks:
  traefik:
    external: true